export function translateName(name) {
    // Translate the name of the pokemon to french
    switch (name) {
        case "bulbasaur":
            return "bulbizarre";
        case "ivysaur":
            return "herbizarre";
        case "venusaur":
            return "florizarre";
        case "charmander":
            return "salamèche";
        case "charmeleon":
            return "reptincel";
        case "charizard":
            return "dracaufeu";
        case "squirtle":
            return "carapuce";
        case "wartortle":
            return "carabaffe";
        case "blastoise":
            return "tortank";
        case "caterpie":
            return "chenipan";
        case "metapod":
            return "chrysacier";
        case "butterfree":
            return "papilusion";
        case "weedle":
            return "aspicot";
        case "kakuna":
            return "coconfort";
        case "beedrill":
            return "dardargnan";
        case "pidgey":
            return "roucool";
        case "pidgeotto":
            return "roucoups";
        case "pidgeot":
            return "roucarnage";
        case "rattata":
            return "rattata";
        case "raticate":
            return "rattatac";
        case "spearow":
            return "piafabec";
        case "fearow":
            return "rapasdepic";
        case "ekans":
            return "abo";
        case "arbok":
            return "arbok";
        case "pikachu":
            return "pikachu";
        case "raichu":
            return "raichu";
        case "sandshrew":
            return "sabelette";
        case "sandslash":
            return "sablaireau";
        case "nidoran-f":
            return "nidoran-f";
        case "nidorina":
            return "nidorina";
        case "nidoqueen":
            return "nidoqueen";
        case "nidoran-m":
            return "nidoran-m";
        case "nidorino":
            return "nidorino";
        case "nidoking":
            return "nidoking";
        case "clefairy":
            return "melofée";
        case "clefable":
            return "mélodelfe";
        case "vulpix":
            return "goupix";
        case "ninetales":
            return "feunard";
        case "jigglypuff":
            return "rondoudou";
        case "wigglytuff":
            return "grodoudou";
        case "zubat":
            return "nosferapti";
        case "golbat":
            return "nosferalto";
        case "oddish":
            return "mystherbe";
        case "gloom":
            return "ortide";
        case "vileplume":
            return "rafflesia";
        case "paras":
            return "paras";
        default:
            return name;
    }
}
